name: Security audit
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '19 0 * * *'
  workflow_dispatch: {} # no parameters
jobs:
  audit:
    runs-on: ubuntu-latest-4-cores
    steps:
      - uses: actions/checkout@v4
      - run: cargo audit
